# Generated by Django 6.0.1 on 2026-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'About Us'), ('privacy_policy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('shipping_delivery', 'Shipping & Delivery'), ('refund_returns', 'Refund and Returns')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Write the full page content here.')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
