# Generated by Django 6.0.1 on 2026-06-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn')], max_length=30)),
                ('url', models.URLField(help_text='Full profile URL (e.g. https://facebook.com/yourpage)')),
                ('chat_handle', models.CharField(blank=True, help_text='For WhatsApp: number with country code (e.g. 8801XXXXXXXXX). For Messenger: your Facebook page username.', max_length=100)),
                ('show_in_chat', models.BooleanField(default=False, help_text='Show this platform in the chat widget?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
