# Generated by Django 6.0.2 on 2026-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
