# Generated by Django 6.0.1 on 2026-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In STock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True),
        ),
    ]
