# Generated by Django 6.0.1 on 2026-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consignment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickup_ready', 'Pickup Ready'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
